[package]
name = "rustpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
log = "0.4.20"
num_enum = "0.7.1"
simple_logger = "4.3.3"
